# Generated by Django 5.2.17 on 2026-09-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendor_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
